dist: bionic
git:
  depth: false
language: node_js
env:
  - COMMITCOUNT="$(git log $(git describe --tags --abbrev=0)..HEAD --oneline|grep -iv 'revert' |grep -e 'fix(' -e 'feat(' -e 'fix:' -e 'feat:' | wc -l | awk '{print $1}')"
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
before_install:
  - git log $(git describe --tags --abbrev=0)..HEAD --oneline
  - echo $COMMITCOUNT
install:
  - npm config set package-lock false
  - make install

jobs:
  include:
    - script:
        - npm run build
      before_script: cd packages/server
      name: build-server
    - script:
        - npm run build
        - bin/run --version
      before_script: cd packages/cli
      name: build-cli
    - script:
        - npm run build
      before_script: cd packages/template
      name: build-template
    - script:
        - npm run test
      before_script: cd packages/server
      name: test-server
    - script:
        - |
          if [ $TRAVIS_PULL_REQUEST == "true" ]; then
          npm run build;
          bin/run --version;
          npm run deploy;
          fi
      before_script:
        - |
          if [ $TRAVIS_PULL_REQUEST == "true" ]; then
          pip install awscli;
          make fake-credentials;
          cd packages/cli;
          fi
      after_script:
        - |
          if [ $TRAVIS_PULL_REQUEST == "true" ]; then
          npm run remove;
          fi
      name: deploy-cli
    - stage: release
      if: (type = push AND branch = master)
      before_script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git fetch pub master
        - git checkout master
      script:
        - if [ $COMMITCOUNT != 0 ]; then
          echo "########create new release########";
          make fake-credentials;
          make publish;
          fi
